image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/crypto-bot-tg/web
  HEROKU_APP_NAME: crypto-bot-tg
  HEROKU_REGISTRY_USER: telegram@sptm.dev
  HEROKU_TOKEN: da4a6967-a955-4a50-8492-38049bfe3117
  CACHE_IMAGE: registry.heroku.com/crypto-bot-tg/web

stages:
  - build

docker-build:
  stage: build
  script:
    - apk add --no-cache curl
    - docker login -u $HEROKU_REGISTRY_USER -p $HEROKU_TOKEN $HEROKU_REGISTRY_IMAGE
    - docker pull $CACHE_IMAGE:crypto-bot-tg || true
    - docker pull $CACHE_IMAGE:production || true
    - docker build
      --platform linux/amd64
      --target crypto-bot-tg:latest
      --cache-from $CACHE_IMAGE:crypto-bot-tg
      --tag $CACHE_IMAGE:crypto-bot-tg
      --file ./Dockerfile
      "."
    - docker build
      --platform linux/amd64
      --cache-from $CACHE_IMAGE:production
      --tag $CACHE_IMAGE:production
      --tag $HEROKU_REGISTRY_IMAGE
      --file ./Dockerfile
      "."
    - docker push $CACHE_IMAGE:crypto-bot-tg
    - docker push $CACHE_IMAGE:production
    - docker login -u -p HEROKU_TOKEN registry.heroku.com
    - docker push $HEROKU_REGISTRY_IMAGE
    - chmod +x ./release.sh
    - ./release.sh
