deploy:
  stage: deploy
  variables:
    HEROKU_APP: crypto-bot-tg
  only:
    - dev
  script:
    - gem install dpl
    - dpl --provider=heroku --app=crypto-bot-tg --api-key=939c73a2-8c1a-42c6-a1e5-fc30a525f985