image: python:3.11

variables:
  HEROKU_APP: crypto-bot-tg
  TG_API_KEY: "TELEGRAM_BOT_API_TOKEN=$TG_API_KEY"

stages:
  - update-api-key
  - deploy

update-api-key:
  stage: update-api-key
  only:
    - dev
  script:
    - touch config.py
    - echo $TG_API_KEY >> ./config.py
    - ./create-venv

deploy:
  stage: deploy
  only:
    - dev
  script:
    - gem install dpl
    - dpl --provider=heroku --app=crypto-bot-tg --api-key=939c73a2-8c1a-42c6-a1e5-fc30a525f985
    - ./start