image: python:3.11

variables:
  HEROKU_APP: crypto-bot-tg
  TG_API_KEY: "TELEGRAM_BOT_API_TOKEN=5041121803:AAHYApDpcK4NN0o6avs33o5cTVUU7ALM42k"

stages:
  - update-api-key
  - deploy

update-api-key:
  stage: update-api-key
  only:
    - dev
  script:
    - touch config.py
    - echo $TG_API_KEY >> ./config.py
    - ./create-venv

deploy:
  stage: deploy
  only:
    - dev
  before_script:
    - apt-get update -y
    - apt-get install -y curl git gnupg
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - |
      cat >~/.netrc <<EOF
      machine api.heroku.com
        login $HEROKU_EMAIL
        password $HEROKU_TOKEN
      machine git.heroku.com
        login $HEROKU_EMAIL
        password $HEROKU_TOKEN
      EOF
    - chmod 600 ~/.netrc
    - heroku git:remote --app $HEROKU_APP
  script:
    - git checkout $CI_COMMIT_SHA
    - git push heroku $CI_COMMIT_SHA:$HEROKU_DEPLOYMENT_BRANCH