# fly.toml file generated for crypto-bot-tg on 2023-02-15T17:15:42+04:00

app = "crypto-bot-tg"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  TELEGRAM_BOT_API_TOKEN = "6128836558:AAGDCRDbkGE_12N_0aEyI4seilPBXfNV8yk"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  tcp_checks = []
