# fly.toml file generated for crypto-bot-tg on 2023-02-15T17:15:42+04:00

app = "crypto-bot-tg"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  TELEGRAM_BOT_API_TOKEN = "6222679707:AAFFC8i8uE72ikPUqkHmAxcAtLn33vVuwlI"
  DB_CONNECTION_URI = "mongodb+srv://fvjfFDFNA:hBAhK4nKwC@sptm.9kxod.mongodb.net/?retryWrites=true&w=majority"
  BOT_ADMIN_ID = "289105332"
  WEBHOOK_URL = "https://cryptobot.sptm.dev"
  WEBHOOK_PATH = "/webhook"
  SERVER_IP_ADDRESS = "127.0.0.1"
  WEBAPP_HOST = "cryptobot.sptm.dev"
  WEBAPP_PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  tcp_checks = []
  internal_port = 8080
  protocol = "tcp"
    [[services.ports]]
      handlers = ["http"]
      port = 80
      force_https = true
    [[services.ports]]
      handlers = ["tls", "http"]
      port = 443
