# fly.toml file generated for crypto-bot-tg on 2023-02-15T17:15:42+04:00

app = "crypto-bot-tg"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  TELEGRAM_BOT_API_TOKEN = "5041121803:AAHYApDpcK4NN0o6avs33o5cTVUU7ALM42k"
  FLYCTL_INSTALL = "/root/.fly"
  PATH = "$FLYCTL_INSTALL/bin:$PATH"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
